### ISSUE TITLE
Compatibility with higher versions

### ISSUE THREAD

**Issue by ArtemBogdanov** [7H3LaughingMan/user-dialogs#1]
**Problem:** The following parameters are specified in module.json
```
"compatibility": {
    "minimum": "11",
    "verified": "11",
    "maximum": "11"
}
```
`compatibility.maximum` indicates that this module cannot be installed on a foundry vtt version higher than the one specified.
But if you take your source code, everything works correctly on v12.

**Proposal:** Could you remove this parameter so your module can be used on a higher version?

**Comment by 7H3LaughingMan** [comment]
Damn, someone actually uses this module?

**Comment by ArtemBogdanov** [comment]
I use this solution to support a more powerful whisper because my players might not notice the whispers in chat.
